name: Setup Go
description: Set up Go
inputs:
  github_token:
    description: Token to use for updating code with formatting fixes
    required: true
  go_version:
    description: The version of Go to use
    required: true

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go_version }}

    - name: Setup private access
      shell: bash
      run: git config --global url.https://${{ inputs.github_token }}@github.com/.insteadOf https://github.com/

    - name: Setup Task
      uses: arduino/setup-task@v1

    - name: Setup Ko
      uses: ko-build/setup-ko@v0.8
